chroma:
  path: "./chroma_db"
  collection_name: "multi_docs_rag"
  hnsw_space: "cosine"

chunking:
  # chunk_type: "static"
  chunk_size: 2048 # 6000 
  chunk_overlap: 512 # 1200
  # chunk_type: "section-based"  # options: static, section-based
  #   max_level_tag : 4

# chunking:
#   strategy: "static"           # or "section-based"

#   static:
#     chunk_size: 2048
#     chunk_overlap: 512

#   section_based:
#     max_level_tag: 4
#     # min_length: 200

retrieval:
  default_k: 1
  min_k: 1
  max_k: 100

generation:
  temperature: 0.7
  top_k: 40
  top_p: 0.9
  repeat_penalty: 1.1
  max_tokens: -1   # -1 means no limit in Ollama